### PR TITLE
Implemented crosshair support for Prime 1 & 2 GC

### PR DESCRIPTION
**Pull request by UltiNaruto**

### CODE REVIEW

**Comment by SirMangler** [comment]
I really like this, it's a feature we've been missing from those two games for a while.

This should be made into a setting. I would add it as an option in PrimeHack GFX. Luckily our recent refactor means toggling groups of code changes is really easy. 

Example: `change_code_group_state("visor_menu", visor ? ModState::DISABLED : ModState::ENABLED);` from line 597.

As for adding it as a setting, it's really quite easy, you can copy what ENABLE_SECONDARY_GUNFX does from HackConfig.cpp:155, search for all references to find the places to define it.

**Comment by UltiNaruto** [comment]
Added to primehack gfx
And also added crosshair color support

**Comment by SirMangler** [comment]
`mp2_gc_static.crosshair_color_address = 0x80738f90;`

Is this address relative to r13? If not, you'll want to find a static pointer path to this unless you have good reason to think it won't change between sessions and worlds.

The only thing this needs is disabling the cursor colour UI (making it read-only/grey) when the `Show GCN Crosshair` setting is disabled. I am perfectly happy to merge it and do that myself.

**Comment by SirMangler** [comment]
Github won't allow me to comment or edit lines to far away from your changes, but after PrimeWidget.cpp:L36 (in the constructor) you need to run `ToggleShowCrosshair(m_toggle_gc_show_crosshair->isChecked());` otherwise when the window is first opened, it won't properly disable the UI until the user toggles the setting.

I wish github didn't have that stupid limitation otherwise I would be able to allow you to add this proposed change with just a button press or at very least reflect it more clearly.

**Comment by SirMangler** [comment]
Brilliant work per the usual.

**Pull request merged**
